### ISSUE TITLE
Løsning af serverproblemer: opsætning af SSL-certifikat (HTTPS)

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#1]
Estimeret tid: 3 timer.

**Comment by fadeto404** [comment]
SSL-certifikatet er sat op. Certifikatet og den tilhørende private key er af sikkerheds hensyn ikke uploadet til Github. De kan findes på serveren. Alle ændringer kan ses i denne [commit](https://github.com/regiongis/SeMaWi/commit/1c8f74c9f0e978f8bd73c02dc24a78401518d36c).

- Der anvendes gratis certifikater (LetsEncrypt) med en varighed på 90 dage.

- Opsætningen af apache2 til at bruge HTTPS findes i `001-semawi.conf`. Der er opsat permanent omdirigering fra HTTP til HTTPS, således at al trafik tvinges til HTTPS.

- For at anvende HTTPS åbnes port 443. Denne mappes også til Docker containerens port 443 i `docker-compose.yml`.

- I `LocalSettings.php` ændres `$wgServer` fra `$wgServer = "http://iotwiki.dk";` til `$wgServer = "//iotwiki.dk";`. Dette gør at wikien ikke længere forventer http, men kan bruge både http og https.

- Apaches SSL-modul aktiveres ved start af containeren i `entrypoint.sh`, med kommandoen `a2enmod ssl`.

**Comment by fadeto404** [comment]
Løses af #13

**Comment by baffioso** [comment]
Er certifikatet udløbet?
![image](https://user-images.githubusercontent.com/7534153/97351602-43fedc80-1892-11eb-8ded-d64804b007c6.png)

**Comment by fadeto404** [comment]
Hmm, det lader det til. Jeg mener egentlig at jeg havde sat en certbot op til at udskifte det, men det er tydeligvis ikke sket.

**Comment by fadeto404** [comment]
Fikset, automatiseret og dokumenteret.
Se [1](https://github.com/regiongis/SeMaWi/commit/1a43bffd0b1a710237ecffc6f94d8d6a41ca4858), [2](https://github.com/regiongis/SeMaWi/commit/38be8fc201c21fef092e6e52f4fa634e741ef358) og [3](https://github.com/regiongis/SeMaWi/commit/d8335b0697bc7a3fd8ec29bbb88659ab4d086658).
