### ISSUE TITLE
Sløv wiki

### ISSUE THREAD

**Issue by baffioso** [regiongis/SeMaWi#10]
@fadeto404 @Ansolong Oplever I også at Wikien igen er blevet ekstremt langsom, når man klikker rundt?

**Comment by fadeto404** [comment]
Ja, det går lidt langsomt. Tjekkede hurtigt htop og fandt en proces der optager 100% CPU. Den lader til at være relateret til Apache.

![cpu-usage-2020-01-17-12-56](https://user-images.githubusercontent.com/16327231/72610884-ddbf5380-3928-11ea-9a4c-66fc4483c5ed.png)

**Comment by baffioso** [comment]
Virker til det går bedre nu. Gjorde du noget?

**Comment by fadeto404** [comment]
En hurtig søgning viser at det er et normalt problem når Apache kører i lang tid af gangen. Har genstartet containeren og har ikke længere problemet.
Jeg kan sætte en automatisk genstart af serveren op hvis I er interesserede (f.eks. kl. 04 om natten hver søndag).

**Comment by baffioso** [comment]
Lyder en god plan. Vil du genstarte apache inde i semawi-containeren eller er det hele serveren?

Vi skal selvfølgelig sikre os at Wiki'en kommer op at køre efter genstart.

**Comment by fadeto404** [comment]
Min umiddelbare tanke var at genstarte hele semawi-containeren - det løste i hvert fald problemet i denne omgang. 
Jeg kan tilføje en funktion til scriptet der efterfølgende tjekker om containeren kører igen efter forsøgt genstart.

**Comment by fadeto404** [comment]
Problemet lader til at være tilbage med et andet procesnavn.
**En ny søgning viser at det højst sandsynligt er malware der miner Bitcoins.**
[Mere info](https://github.com/docker-library/redis/issues/217)
![cpu-usage-2020-01-22-09-58](https://user-images.githubusercontent.com/16327231/72879746-ceac1d00-3cfd-11ea-8812-e118b50f3428.png)

Processerne `/tmp/kdevtmpfsi` og `/var/tmp/kinsing` er synderne.

**Comment by baffioso** [comment]
Uha. Har du fundet løsninger på at få fjernet den malware?

Vi skal også finde ud af at få lukket de huller der er kommet ind af.

**Comment by fadeto404** [comment]
Der er en del forslag i det link jeg har vedlagt, og flere melder positive resultater tilbage så jeg er optimistisk omkring at få det fjernet.

Mht. hvordan det er kommet ind kan jeg indtil videre sige at det er Docker-relateret, men det er alt hvad jeg har indtil videre.

**Comment by baffioso** [comment]
@Ansolong tænker at denne er ret central at få styr på.

**Comment by fadeto404** [comment]
Jeg har lavet nogle ændringer inde i `semawi-mediawiki` containeren (dokumentation følger) der skulle forhindre malwaren i at køre. Jeg vil holde øje med det lidt endnu for at være sikker på at det virker efter hensigten. 

Jeg kan ikke garantere at den ikke kan komme igen, da jeg ikke har fundet ud af hvordan den er kommet ind.
Den lader til kun at have inficeret `semawi-mediawiki` containeren og ikke resten af systemet. Det tyder på at #3 vil kræve væsentligt mere arbejde end først antaget for at sikre at det ikke sker igen.

**Comment by fadeto404** [comment]
> Jeg har lavet nogle ændringer inde i `semawi-mediawiki` containeren (**dokumentation følger**) der skulle forhindre malwaren i at køre.

Til fremtidig reference. Fremgangsmåde:

0. Kør følgende for at finde involverede filer: `sudo find / -type f -exec grep -l "kdevtmpfsi" {} +`
1. Åben containeren: `docker exec -it semawi-mediawiki bash` 
2. Tjek `crontab` - den kørte et script hvert minut som startede processen:
  a. Tjek eventuelt først om der er suspekt aktivitet hvor `cron` er involveret: `sudo grep CRON /var/log/syslog`
  b. Følgende vil gå gennem `crontab` for alle brugere og finde eventuelle cronjobs for hver bruger:
  `for user in $(cut -f1 -d: /etc/passwd); do crontab -u $user -l; done`
  Dette afslørede et cronjob kørt af brugeren `www-data`.
3. Fjern cronjobbet med: `crontab -e -u www-data`
4. Nægt `www-data` at lave cronjobs fremover med: `echo "www-data" >> /etc/cron.deny`
5. Fjern filer: `rm -rf /tmp/kdevtmpfsi /var/tmp/kinsing`
6. Opret nye, tommer filer med samme navn og placering: `touch /tmp/kdevtmpfsi && touch /var/tmp/kinsing`
7. Juster rettigheder så de nyligt oprettede tommer filer ikke kan ændres af malwaren: 
`chmod go-rwx /var/tmp`
`chmod 1777 /tmp`

Dette bør forhindre malwaren i at køre, men hullet den er kommet ind af bør stadig findes og lukkes.

**Comment by Ansolong** [comment]
Det var da godt du opdagede det, Rasmus. Der er vel ikke så mange alternativer til at bruge nogle timer på at løse denne her, tænker jeg. Håber ikke det bliver alle de resterende timer der kommer til at gå til det.

**Comment by fadeto404** [comment]
Efter en del research og timer brugt på log-crawling er det endelig lykkedes at finde hullet. Det er ret kritisk, men har lavet en midlertidig løsning der lukker det indtil videre. Mere dokumentation kommer snart.

**Comment by fadeto404** [comment]
Problemet lå i `/var/www/wiki/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php`.
Filens indhold er:
```php
<?php
eval('?>' . file_get_contents('php://input'));
```
Dette script er offentligt tilgængelig, og gør en i stand til at køre php-kode på serveren, hvilket i princippet giver angribere direkte shell-adgang. Scriptet er en del af PHPUnit, et system til test, som aldrig bør være en del af et produktionsmiljø. Jeg er ikke 100% sikker på hvorfor det er der, men ifølge udvikleren af systemet er det skidt:

![image](https://user-images.githubusercontent.com/16327231/73529955-db282800-4417-11ea-87f4-9ab9a1d555da.png)
Se også: ["... if your vendor directory is publicly accessible on your webserver then your deployment process is also broken."](https://phpunit.readthedocs.io/en/8.4/installation.html#webserver)

**Hurtig, midlertidig fix**
En midlertidig fix indtil der blev lukket af for den omtalte `vendor` mappe:
`chmod 000 /var/www/wiki/vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php`

Log-entries i `/var/log/apache2/access.log` der satte mig på sporet var:
```
...
113.206.181.27 - - [29/Jan/2020:02:00:22 +0000] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 200 203 "-" "Python-urllib/2.7"
...
193.187.174.104 - - [29/Jan/2020:02:36:27 +0000] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 200 299 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
193.187.174.104 - - [29/Jan/2020:02:36:31 +0000] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 200 166 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
...
```

Hullet er blevet udnyttet af flere angribere gennem tiden til at køre flere forskellige ting - har eksempelvis log-entries fra bl.a. kinesiske, russiske og lettiske IP-adresser der har udnyttet hullet, alle tre i løbet af bare en enkelt time.

**Comment by fadeto404** [comment]
Lukkes af https://github.com/regiongis/SeMaWi/blob/70b5b82d3b25a4aeadb1b725c98e40111a75b022/apache2.conf#L251-L257
Dette forhindrer al adgang til `/var/www/wiki/vendor` mappen.

**Comment by baffioso** [comment]
Godt arbejde. Så håber vi der ikke er flere huller.
