### ISSUE TITLE
Indsæt IoT logo

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#11]

**Comment by fadeto404** [comment]
Løst ved at ændre variablen `$wgLogo` i `LocalSettings.php` til `$wgLogo = "$wgScriptPath/resources/assets/iotwiki_logo.png";`, samt ved at ændre stien til logoets volume i `docker-compose.yml`.
Krævede desuden at skalere logoet til 135x135 px.

Se også den [officielle dokumentation](https://www.mediawiki.org/wiki/Manual:$wgLogo) for ændring af logo.

**Comment by fadeto404** [comment]
Løses af #13
