### ISSUE TITLE
Fælles kodeord/spørgsmål ved oprettelse af bruger

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#12]
Ved oprettelse af bruger skal der indtastes et fælles kendt kodeord eller svares på et spørgsmål, så f.eks. bots forhindres i at oprette kunstige profiler. Kan det gøres uden mundtlig overlevering af svaret, er det at foretrække.

**Comment by fadeto404** [comment]
Løst ved at inkludere udvidelsen [QuestyCaptcha](https://www.mediawiki.org/wiki/Extension:QuestyCaptcha). 

- Der er et enkelt spørgsmål inkluderet med tilhørende svar. Det er muligt at slå Captcha til i en række forskellige tilfælde (redigeringer, tilføjelse af eksterne links, etc.). Flere spørgsmål kan tilføjes ved at ændre i `LocalSettings.php`.

- På nuværende tidspunkt skal der udfyldes en Captcha ved brugeroprettelse og efter fejlet login. Dette kan ændres i `LocalSettings.php`

- Der er som udgangspunkt ikke danske meddelelser i udvidelsen. De tilføjes derfor af [denne commit](https://github.com/regiongis/SeMaWi/commit/3049514c49bad99cc0de5c08df29f95580606e8d). Meddelelserne kan ændres af administratorer ved at navigere til [specialsiden for systemmeddelelser](https://iotwiki.dk/index.php?title=Speciel:MediaWiki-systemmeddelelser) og søge efter "questy". Meddelelserne ændres ved at klikke på linket til meddelelsen og redigere siden.

**Comment by fadeto404** [comment]
Løses af #13
