### ISSUE TITLE
Løsning af serverproblemer: Korrigering af DNS (Domænenavn og IP)

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#2]

**Comment by fadeto404** [comment]
Løst ved tilrettelse af konfiguration af `$wgServer` i LocalSettings.php i containeren. Den er sat til "http://iotwiki.dk"
https://github.com/regiongis/SeMaWi/blob/4bcaacad58fb08f3dd796e36a5421cdc8dfa0590/mutables/LocalSettings.php#L32
