### ISSUE TITLE
IoT wiki: Oprettelse af Backup

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#4]
Estimeret tid: 6-7 timer

**Comment by fadeto404** [comment]
Backup kører. Der bliver lavet en backup hver nat kl.3, og backups ældre end 30 dage bliver automatisk fjernet. Det er lavet som beskrevet i [README](https://github.com/regiongis/SeMaWi#mysql), med et par mindre konfigurationer. Det er testet at både backup og fjernelse af 30+ dage gamle backups fungerer.

Backups af databasen bliver lagt i `/srv/semawi/backup/`.
