### ISSUE TITLE
Fejler når der forsøges at oprette ny bruger

### ISSUE THREAD

**Issue by baffioso** [regiongis/SeMaWi#5]
Kan evt. se om skiftet til den nyeste version af wikien løser denne?

**Comment by fadeto404** [comment]
Fejlen er relateret til emails. Det er pt. muligt at oprette brugere uden emails. 
Opdaterer når jeg ved mere.

**Comment by fadeto404** [comment]
> Fejlen er relateret til emails.

Der opstod fejl ved oprettelse af brugere når man indtastede emails, da Mediawiki forsøger at sende en bekræftelses-mail til den angivne mail-adresse. Da der ikke er sat mailsystem op på serveren endnu resulterede det i en fejl.

Jeg har derfor midlertidigt slået email-bekræftelse fra, indtil vi får løst #6 
Det gøres i `LocalSettings.php` ved at indsætte linjen `$wgEmailAuthentication = false;`

**Comment by fadeto404** [comment]
Lukker issuet indtil videre, og arbejder videre med #6.
