### ISSUE TITLE
Opsætning af automatisk mail-system

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#6]
Opsætning af automatisk mail-system, så 
- [x] 1) brugere kan notificeres om ændringer på sider pr. mail.

**Comment by fadeto404** [comment]
En løsning der ikke bruger gmail, kunne måske være [Amazons SES](https://aws.amazon.com/ses/)

**Comment by baffioso** [comment]
Er det gratis?

**Comment by fadeto404** [comment]
I praksis er det gratis. De skriver: 

> "And, if you send from an application hosted in Amazon EC2, the first 62,000 emails you send every month are free."

**Comment by baffioso** [comment]
Tja, den bliver svær at gå over.

**Comment by baffioso** [comment]
Tænker du bare vurdere hvad der giver mest mening ifht. til google eller amazon.

**Comment by fadeto404** [comment]
Mail systemet er oppe at køre nu. Jeg har testet at email-bekræftelse, samt notifikationer om ændringer nu fungerer. I er velkomne til at teste og melde evt. fejl tilbage.

Valgte at bruge Gmail da jeg ikke har indgående erfaring med Amazon SES. Setup af dette sker i `Localsettings.php` (mere indgående dokumentation følger i `README`).

Vi skal lige finde ud af at overføre gmail-kontoinfo.

**Comment by Ansolong** [comment]
Det lyder godt. Jeg kan altså fortælle folk, at de godt kan tilføje mail til deres brugerkonto?

**Comment by fadeto404** [comment]
Ja, det kan du.

**Comment by baffioso** [comment]
@fadeto404 Prøvede lige at tilknytte en mail til min wiki konto, men får denne fejl:
![image](https://user-images.githubusercontent.com/7534153/73264736-bc395400-41d3-11ea-831d-4f18ba83b080.png)

**Comment by baffioso** [comment]
Den har dog registreret min mail, så virker trods fejlmeddelelse

**Comment by fadeto404** [comment]
Har ikke kunnet reproducere fejlen, og har ikke fundet noget nævneværdigt i loggen. Det var nok bare en midlertidig fejl som der står i meddelelsen, men du må endelig sige til hvis den viser sig igen.
