### ISSUE TITLE
Deleted: Bot-test ved oprettelse af bruger

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#8]
Brugere skal selv kunne oprette sig på wikien, men skal gennem en bot-test og bekræfte, at de er et rigtigt menneske. Det kunne enten være ved en "skriv tekst fra et billede" eller indtastning af et kendt kodeord, som mundtligt gives videre til nye brugere.

**Comment by fadeto404** [comment]
At skrive tekst fra et billede er typisk ikke særligt effektivt til at holde bots ude.
Jeg vil foreslå at man i stedet bruger en løsning hvor der skal svares på et spørgsmål. 
Det kan gøres effektivt uden at der behøver at være administratorer inde over, til at videregive svaret. På den måde kan man få det bedste af begge verdener.

**Comment by Ansolong** [comment]
Lyder som en god løsning med et spørgsmål der skal svares på.
