### ISSUE TITLE
Bekræft, at man har læst code of conduct

### ISSUE THREAD

**Issue by Ansolong** [regiongis/SeMaWi#9]
Oprettelse af en 'jeg har læst og forstået code of conduct' knap, som skal markeres, når man opretter en bruger.

**Comment by baffioso** [comment]
Har tilføjet denne samt #8 til V2 milestone. Tænker at det giver mening at få lukket opgaverne i V1 inden disse laves. Kan også være issues i V1 afføder nye issues som kan oprettes i V2. @Ansolong @fadeto404 hvad tænker I?

**Comment by fadeto404** [comment]
Lyder fornuftigt

**Comment by fadeto404** [comment]
Løses ved brug af udvidelsen [NewSignupPage](https://www.mediawiki.org/wiki/Extension:NewSignupPage).

- Udvidelsen tilføjer en checkbox ved brugeroprettelse hvor man skal acceptere vilkårene for at oprette en bruger.

- Automatisk installation ved første start af container løses af [denne commit](https://github.com/regiongis/SeMaWi/commit/ed490a02ea4a806aebce6e0bcc138bf34ec190bb). Dette foregår på samme måde som de andre udvidelser, ved at downloade udvidelsen, og vælge version i scriptet `entrypoint.sh`. Udvidelsen loades i `LocalSettings.php`.

- Meddelelser er i samme commit redigeret til at linke til IoT wikis [code of conduct](https://iotwiki.dk/index.php?title=Code_of_Conduct).

**Comment by fadeto404** [comment]
Løses af #13
